### ISSUE TITLE
Dynamically change color of the spinner

### ISSUE THREAD

**Issue by idanb11** [urish/angular-spinner#27]
Hi @urish 
I'm trying to update the color of the spinner while it's already being spinning.
Is it possible to do that already? or needs to add that functionally?
What i'm doing now is set on the controller scope the options object and when i receive data from the server I update the options object - which clearly don't work.

Any suggestions?

Thanks,
Idan,

**Comment by Attrash-Islam** [comment]
Hi @idanb11 ,
Thanks for reporting

As I saw that spin.js doesn't give you the opportunity to change colors dynamically.
This wrapper library is to wrap spin.js functionality into the angular life, so I don't think there's a reason to add feature like that.

But you can use workaround :)

```html
<div id="test">
   <span us-spinner></span>
</div>
```

```css
#test [us-spinner] div {
          background: rgb(214, 15, 15) !important; //Red spinner
    }
```

If you encounter any issues reopen the issue
