### ISSUE TITLE
How to place a spinner at fixed position and prevent scrolling?

### ISSUE THREAD

**Issue by zhekaus** [urish/angular-spinner#56]

**Comment by sahalswappo** [comment]
did you try position:'fixed' inside us-spinner ?

**Comment by Attrash-Islam** [comment]
Hi @zhekaus ,

Enter this plunker:
http://plnkr.co/edit/BGLUYcylbIVJRz6ztbhf?p=preview

Add a style tag
```css
.prevent-scroll {
      overflow: hidden;
      height: 100%;
}
```

Add this div at the end of the body (last body children) - to ensure scrollable area
```html
<div style="margin-top: 1000px; margin-bottom: 100px"> 
        Some sort of huge thing
</div>
```

If any tag have `prevent-scroll` class, then you'll not be able to scroll in that particular element

with the power of the angularjs, you can add `ng-class` attribute in the body tag with the following rules:
```html
<body ng-app="myapp" ng-controller="MyController" ng-class="{'prevent-scroll': spinneractive}">
 ...
</body>
```

and you will need to fix the position of the spinner by applying this style rule:
```css
.spinner {
      position: fixed !important;
}
```

which will apply for all us-spinners in the page
